/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algvis;

/**
 *
 * @author Kenpachi
 */
public class Panel extends javax.swing.JFrame {
    
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubbleSortButton = new javax.swing.JButton();
        selectionSortButton = new javax.swing.JButton();
        quickSortButton = new javax.swing.JButton();
        insertionSortButton = new javax.swing.JButton();
        seperator = new javax.swing.JSeparator();
        linearSearchButton = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        binarySearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bubbleSortButton.setText("Bubble Sort");
        bubbleSortButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bubbleSortButtonMouseClicked(evt);
            }
        });

        selectionSortButton.setText("Selection Sort");
        selectionSortButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectionSortButtonMouseClicked(evt);
            }
        });

        quickSortButton.setText("Quick Sort");
        quickSortButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quickSortButtonMouseClicked(evt);
            }
        });

        insertionSortButton.setText("Insertion Sort");
        insertionSortButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertionSortButtonMouseClicked(evt);
            }
        });

        seperator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        linearSearchButton.setText("Linear Search");
        linearSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linearSearchButtonMouseClicked(evt);
            }
        });

        speedSlider.setMaximum(1000);
        speedSlider.setMinimum(1);
        speedSlider.setMinorTickSpacing(50);
        speedSlider.setPaintLabels(true);
        speedSlider.setPaintTicks(true);
        speedSlider.setSnapToTicks(true);

        jLabel1.setText("Fast");

        jLabel2.setText("Slow");

        binarySearchButton.setText("Binary Search");
        binarySearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binarySearchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectionSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bubbleSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertionSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quickSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(linearSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(binarySearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bubbleSortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectionSortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quickSortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertionSortButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(linearSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(binarySearchButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bubbleSortButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubbleSortButtonMouseClicked
        Sort sort = new Sort();
        sort.setSortType("Bubble");
        sort.setWaitTime(speedSlider.getValue());
        Thread SortThread = new Thread(sort);
        SortThread.start();
    }//GEN-LAST:event_bubbleSortButtonMouseClicked

    private void selectionSortButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionSortButtonMouseClicked
        Sort sort = new Sort();
        sort.setSortType("Selection");
        sort.setWaitTime(speedSlider.getValue());
        Thread SortThread = new Thread(sort);
        SortThread.start();
    }//GEN-LAST:event_selectionSortButtonMouseClicked

    private void quickSortButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSortButtonMouseClicked
        Sort sort = new Sort();
        sort.setSortType("Quick");
        sort.setWaitTime(speedSlider.getValue());
        Thread SortThread = new Thread(sort);
        SortThread.start();
    }//GEN-LAST:event_quickSortButtonMouseClicked

    private void insertionSortButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertionSortButtonMouseClicked
        Sort sort = new Sort();
        sort.setSortType("Insertion");
        sort.setWaitTime(speedSlider.getValue());
        Thread SortThread = new Thread(sort);
        SortThread.start();
    }//GEN-LAST:event_insertionSortButtonMouseClicked

    private void linearSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linearSearchButtonMouseClicked
        LinearSearch search = new LinearSearch();
        search.setSearchType("Linear");
        search.setWaitTime(speedSlider.getValue());
        Thread SearchThread = new Thread(search);
        SearchThread.start();
    }//GEN-LAST:event_linearSearchButtonMouseClicked

    private void binarySearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarySearchButtonMouseClicked
        BinarySearch search = new BinarySearch();
        search.setSearchType("Binary");
        search.setWaitTime(speedSlider.getValue());
        Thread SearchThread = new Thread(search);
        SearchThread.start();
    }//GEN-LAST:event_binarySearchButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton binarySearchButton;
    private javax.swing.JButton bubbleSortButton;
    private javax.swing.JButton insertionSortButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton linearSearchButton;
    private javax.swing.JButton quickSortButton;
    private javax.swing.JButton selectionSortButton;
    private javax.swing.JSeparator seperator;
    private javax.swing.JSlider speedSlider;
    // End of variables declaration//GEN-END:variables
}
